
eureka:
  instance:
    #lease-renewal-interval-in-seconds: 1
    #lease-expiration-duration-in-seconds: 2
    #register-with-eureka: true
    #register-with-eureka: true
    hostname: localhost
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration:5
